import { displayUrl } from './typst';
import { visibleSections, type ResumeData, type TemplateId } from './types';

/**
 * The same resume as a LaTeX file, for Overleaf (compiles with pdfLaTeX, Overleaf's default).
 * Layout follows the widely used ATS-friendly "Jake's resume" structure (MIT), adapted per template.
 */

/** Escapes LaTeX special characters and drops symbols pdfLaTeX's default fonts can't print. */
export function latexText(value: string): string {
  return value
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/[^\x20-\x7E\u00A0-\u017F\u2013\u2014\u2018\u2019\u201C\u201D\u2022\u2026\u20AC]/g, '')
    .replace(/\\/g, '\u0000')
    .replace(/([&%$#_{}])/g, '\\$1')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}')
    .replace(/\u0000/g, '\\textbackslash{}');
}
const latexUrl = (url: string) => (/^(https?:|mailto:)/i.test(url) ? url : `https://${url}`).replace(/([%#\\])/g, '\\$1');

const FONTS: Record<TemplateId, string> = {
  classic: '% Font: Computer Modern (LaTeX default)',
  modern: '\\usepackage[scaled]{helvet}\n\\renewcommand{\\familydefault}{\\sfdefault}',
  compact: '\\usepackage{mathptmx} % Times',
  minimal: '\\usepackage[scaled]{helvet}\n\\renewcommand{\\familydefault}{\\sfdefault}',
};
const SIZES: Record<TemplateId, string> = { classic: '11pt', modern: '10pt', compact: '10pt', minimal: '10pt' };
const MARGINS: Record<TemplateId, string> = { classic: '1.5cm', modern: '1.6cm', compact: '1.2cm', minimal: '1.8cm' };

const SECTION_FORMAT: Record<TemplateId, string> = {
  classic: '\\titleformat{\\section}{\\vspace{-4pt}\\scshape\\raggedright\\large}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]',
  modern: '\\titleformat{\\section}{\\vspace{-4pt}\\bfseries\\color{accent}\\raggedright\\small}{}{0em}{\\MakeUppercase}[\\color{black!25}\\titlerule \\vspace{-5pt}]',
  compact: '\\titleformat{\\section}{\\vspace{-6pt}\\bfseries\\raggedright}{}{0em}{\\MakeUppercase}[\\titlerule \\vspace{-6pt}]',
  minimal: '\\titleformat{\\section}{\\vspace{2pt}\\bfseries\\raggedright\\large}{}{0em}{}[\\vspace{-2pt}]',
};

const nonEmpty = (items: string[]) => items.map((item) => item.trim()).filter(Boolean);

export function toLatex(data: ResumeData, template: TemplateId): string {
  const { basics } = data;
  const out: string[] = [];
  const paper = data.layout.paper === 'us-letter' ? 'letterpaper' : 'a4paper';
  out.push(
    `% ${basics.name || 'Resume'} — generated by the portfolio Resume builder (template: ${template}).`,
    '% Compiles with pdfLaTeX (Overleaf default). Structure based on "Jake\'s resume" (MIT).',
    `\\documentclass[${paper},${SIZES[template]}]{article}`,
    '\\usepackage[T1]{fontenc}',
    '\\usepackage[utf8]{inputenc}',
    FONTS[template],
    `\\usepackage[margin=${MARGINS[template]}]{geometry}`,
    '\\usepackage{titlesec}',
    '\\usepackage[usenames,dvipsnames]{xcolor}',
    '\\usepackage{enumitem}',
    '\\usepackage[hidelinks]{hyperref}',
    '\\usepackage{tabularx}',
    '\\input{glyphtounicode}',
    '\\pdfgentounicode=1 % makes the PDF text readable by ATS',
    '\\definecolor{accent}{HTML}{1D4ED8}',
    '\\pagestyle{empty}',
    '\\raggedright',
    '\\setlength{\\tabcolsep}{0in}',
    '\\setlength{\\parindent}{0pt}',
    SECTION_FORMAT[template],
    '\\setlist[itemize]{leftmargin=0.15in, label={\\textbullet}, itemsep=1pt, topsep=2pt, parsep=0pt}',
    '',
    '% \\entry{title}{date}  and  \\entrysub{title}{date}{subtitle}{location}',
    '\\newcommand{\\entry}[2]{\\vspace{2pt}\\begin{tabularx}{\\linewidth}{X r}\\textbf{#1} & #2 \\\\ \\end{tabularx}\\vspace{-4pt}}',
    '\\newcommand{\\entrysub}[4]{\\vspace{2pt}\\begin{tabularx}{\\linewidth}{X r}\\textbf{#1} & #2 \\\\ \\textit{\\small #3} & \\textit{\\small #4} \\\\ \\end{tabularx}\\vspace{-4pt}}',
    '',
    '\\begin{document}',
    '',
  );

  const contact = [
    basics.phone ? latexText(basics.phone) : '',
    basics.email ? `\\href{mailto:${latexUrl(basics.email.trim()).replace(/^https:\/\//, '')}}{${latexText(basics.email)}}` : '',
    basics.location ? latexText(basics.location) : '',
    ...basics.links.filter((link) => link.url.trim()).map((link) => `\\href{${latexUrl(link.url.trim())}}{${latexText(displayUrl(link.url))}}`),
  ].filter(Boolean);
  const centered = template === 'classic' || template === 'compact';
  out.push(centered ? '\\begin{center}' : '\\begin{flushleft}');
  out.push(`  {\\Huge ${template === 'classic' ? '\\scshape ' : '\\bfseries '}${latexText(basics.name || 'Your Name')}} \\\\ \\vspace{3pt}`);
  if (basics.headline.trim()) out.push(`  {\\large ${template === 'modern' ? '\\color{accent}' : ''}${latexText(basics.headline)}} \\\\ \\vspace{2pt}`);
  if (contact.length) out.push(`  \\small ${contact.join(' $|$ ')}`);
  out.push(centered ? '\\end{center}' : '\\end{flushleft}', '');

  const entry = (title: string, date: string, subtitle: string, location: string) => (subtitle.trim() || location.trim()
    ? `\\entrysub{${latexText(title)}}{${date}}{${latexText(subtitle)}}{${latexText(location)}}`
    : `\\entry{${latexText(title)}}{${date}}`);
  const itemize = (items: string[]) => (nonEmpty(items).length
    ? ['\\begin{itemize}', ...nonEmpty(items).map((item) => `  \\item ${latexText(item)}`), '\\end{itemize}'].join('\n')
    : '');

  for (const id of visibleSections(data)) {
    const lines: string[] = [];
    if (id === 'summary' && basics.summary.trim()) {
      lines.push('\\section{Summary}', latexText(basics.summary));
    }
    if (id === 'experience') {
      const items = data.experience.filter((item) => !item.hidden && (item.role.trim() || item.company.trim()));
      if (items.length) {
        lines.push('\\section{Experience}');
        for (const item of items) {
          lines.push(entry(item.role, latexText(item.period), item.company, item.location), itemize(item.bullets));
        }
      }
    }
    if (id === 'projects') {
      const items = data.projects.filter((item) => !item.hidden && item.name.trim());
      if (items.length) {
        lines.push('\\section{Projects}');
        for (const item of items) {
          const link = item.link.trim() ? `\\href{${latexUrl(item.link.trim())}}{${latexText(displayUrl(item.link))}}` : '';
          lines.push(entry(item.name, link, item.tech, ''), itemize(item.bullets));
        }
      }
    }
    if (id === 'skills') {
      const groups = data.skills.filter((group) => group.items.trim());
      if (groups.length) {
        lines.push('\\section{Skills}', groups.map((group) => (group.group.trim()
          ? `\\textbf{${latexText(group.group)}:} ${latexText(group.items)}`
          : latexText(group.items))).join(' \\\\\n'));
      }
    }
    if (id === 'education') {
      const items = data.education.filter((item) => item.school.trim() || item.degree.trim());
      if (items.length) {
        lines.push('\\section{Education}');
        for (const item of items) {
          lines.push(entry(item.school, latexText(item.period), item.degree, item.location));
          if (item.details.trim()) lines.push(`{\\small ${latexText(item.details)}}`);
        }
      }
    }
    if (id === 'extras') {
      for (const extra of data.extras.filter((block) => block.title.trim() && nonEmpty(block.items).length)) {
        lines.push(`\\section{${latexText(extra.title)}}`, itemize(extra.items));
      }
    }
    if (lines.length) out.push(...lines.filter(Boolean), '');
  }

  out.push('\\end{document}', '');
  return out.join('\n');
}
