CREATE TABLE IF NOT EXISTS Profile (
  id INTEGER PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL, location TEXT NOT NULL,
  available BOOLEAN NOT NULL DEFAULT 1, summary TEXT NOT NULL, yearsExperience TEXT NOT NULL,
  profileImage TEXT NOT NULL, productsShipped TEXT NOT NULL, performanceMetric TEXT NOT NULL,
  lighthouse TEXT NOT NULL, usersImpacted TEXT NOT NULL, socialLinks TEXT NOT NULL,
  targetRoles TEXT NOT NULL DEFAULT '', workPreference TEXT NOT NULL DEFAULT '', availability TEXT NOT NULL DEFAULT '',
  noticePeriod TEXT NOT NULL DEFAULT '', assistantNotes TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS SiteCopy (id INTEGER PRIMARY KEY, content TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS SkillGroup (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, items TEXT NOT NULL, "order" INTEGER NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS Experience (id INTEGER PRIMARY KEY AUTOINCREMENT, role TEXT NOT NULL, company TEXT NOT NULL, period TEXT NOT NULL, current BOOLEAN NOT NULL DEFAULT 0, bullets TEXT NOT NULL, "order" INTEGER NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS Project (id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT NOT NULL UNIQUE, title TEXT NOT NULL, description TEXT NOT NULL, stack TEXT NOT NULL, featured BOOLEAN NOT NULL DEFAULT 0, type TEXT NOT NULL DEFAULT 'case-study', image TEXT NOT NULL DEFAULT '', liveUrl TEXT NOT NULL DEFAULT '', repoUrl TEXT NOT NULL DEFAULT '', externalUrl TEXT NOT NULL DEFAULT '', objective TEXT NOT NULL DEFAULT '', approach TEXT NOT NULL DEFAULT '', architecture TEXT NOT NULL DEFAULT '', result TEXT NOT NULL DEFAULT '', content TEXT NOT NULL DEFAULT '', published BOOLEAN NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS Resume (id INTEGER PRIMARY KEY, fileName TEXT NOT NULL, mimeType TEXT NOT NULL, size INTEGER NOT NULL, data BLOB NOT NULL, uploadedAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ProfileImage (id INTEGER PRIMARY KEY, fileName TEXT NOT NULL, mimeType TEXT NOT NULL, size INTEGER NOT NULL, data BLOB NOT NULL, uploadedAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ProjectImage (slug TEXT PRIMARY KEY, fileName TEXT NOT NULL, mimeType TEXT NOT NULL, size INTEGER NOT NULL, data BLOB NOT NULL, uploadedAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS User (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL DEFAULT '', passwordHash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'admin', tokenVersion INTEGER NOT NULL DEFAULT 0, permissions TEXT NOT NULL DEFAULT '', readOnly BOOLEAN NOT NULL DEFAULT 0, createdAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Event (id INTEGER PRIMARY KEY AUTOINCREMENT, type TEXT NOT NULL, detail TEXT NOT NULL DEFAULT '', createdAt TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS Event_type_createdAt ON Event (type, createdAt);
CREATE TABLE IF NOT EXISTS AiProvider (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, kind TEXT NOT NULL, baseUrl TEXT NOT NULL, model TEXT NOT NULL, keyCipher TEXT NOT NULL DEFAULT '', keyHint TEXT NOT NULL DEFAULT '', enabled BOOLEAN NOT NULL DEFAULT 1, "order" INTEGER NOT NULL DEFAULT 0, temperature TEXT NOT NULL DEFAULT '', createdAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Setting (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ResumeDocument (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, template TEXT NOT NULL DEFAULT 'classic', data TEXT NOT NULL, code TEXT, jobDescription TEXT NOT NULL DEFAULT '', createdAt TEXT NOT NULL, updatedAt TEXT NOT NULL);
