import type React from 'react';
import Link from 'next/link';
import type { PortfolioData } from '@/lib/portfolio';
import { InteractionLayer } from './interaction-layer';

function FaceButton({ label, tone = 'a', compact = false }: { label: string; tone?: 'a' | 'b' | 'x' | 'y'; compact?: boolean }) {
  return <span aria-hidden="true" className={`xbox-face-button xbox-face-button--${tone}${compact ? ' xbox-face-button--compact' : ''}`}>{label}</span>;
}

export function PortfolioHome({ data }: { data: PortfolioData }) {
  const copy = data.copy;
  return <main className="portfolio-shell min-h-screen bg-[#030609] text-slate-100"><InteractionLayer name={data.profile.name} profileImage={data.profile.profileImage} socialLinks={data.profile.socialLinks} role={data.profile.role} location={data.profile.location} summary={data.profile.summary}/><div className="lg:pl-64"><header className="site-header sticky top-0 z-20 border-b border-white/10 bg-[#030609]/80 px-4 py-3 backdrop-blur lg:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between text-[10px] font-bold uppercase tracking-wider"><span className="text-lime-300">{copy.header[0]}</span><span className="hidden text-slate-500 md:block">{copy.header[1]}</span><span className="text-cyan-300">{copy.header[2]}</span><span className="hidden text-slate-400 md:block">{copy.header[3]}</span></div></header><div className="mx-auto max-w-7xl px-4 py-5 md:px-8">
    <section id="home" className="game-grid relative scroll-mt-24 overflow-hidden rounded-3xl border border-white/10 bg-[#050c12] px-6 py-10 md:px-10 md:py-16"><div className="relative z-10 max-w-2xl"><p className="font-mono text-lg text-lime-300">{copy.hero.greeting}</p><h1 className="mt-2 text-5xl font-black uppercase tracking-tight md:text-7xl">{data.profile.name}</h1><p className="mt-2 text-sm font-black uppercase tracking-[.3em] text-cyan-300 md:text-lg">{data.profile.role}</p><p className="mt-6 max-w-xl text-base leading-7 text-slate-300">{data.profile.summary}</p><div className="mt-6 flex flex-wrap gap-2">{copy.hero.technologies.map(x => <span key={x} className="hero-skill-tag rounded-full border border-white/10 bg-white/[.03] px-3 py-1.5 text-xs text-slate-200">{x}</span>)}</div><div className="mt-8 flex flex-wrap gap-3"><a href="#projects" className="inline-flex items-center gap-3 rounded-xl bg-lime-300 px-5 py-3 text-xs font-black text-black">{copy.hero.primaryAction} <FaceButton label="A" /></a><a href="#about" className="inline-flex items-center gap-3 rounded-xl border border-white/20 px-5 py-3 text-xs font-black hover:border-cyan-300">{copy.hero.secondaryAction} <FaceButton label="X" tone="x" /></a></div><div className="mt-7 flex gap-5 text-xs text-slate-400"><span>● <span className="text-lime-300">{copy.hero.availability}</span></span><span>⌖ {data.profile.location}</span></div></div><div className="absolute bottom-8 right-8 hidden w-80 rounded-2xl border border-lime-300/20 bg-black/40 p-5 font-mono text-xs leading-6 text-slate-300 md:block">{copy.hero.terminalLines.map(line => <div key={line}><span className="text-lime-300">&gt;</span> {line}</div>)}</div></section>
    <section id="about" className="scroll-mt-24 py-6"><div className="grid gap-3 md:grid-cols-5">{[[data.profile.yearsExperience,copy.statsLabels[0]],[data.profile.productsShipped,copy.statsLabels[1]],[data.profile.performanceMetric,copy.statsLabels[2]],[data.profile.lighthouse,copy.statsLabels[3]],[data.profile.usersImpacted,copy.statsLabels[4]]].map(([value,label]) => <div key={label} className="rounded-2xl border border-white/10 bg-[#071018] p-5"><div className="text-2xl font-black text-white">{value}</div><div className="mt-2 text-[10px] font-bold tracking-wider text-slate-500">{label}</div></div>)}</div></section>
    <section id="skills" className="scroll-mt-24 py-6"><div className="rounded-3xl border border-white/10 bg-[#071018] p-6"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.25em] text-lime-300">{copy.skills.eyebrow}</p><h2 className="mt-2 text-2xl font-black">{copy.skills.title}</h2></div><span className="text-xs text-slate-500">{copy.skills.description}</span></div><div id="engineering" className="mt-6 grid gap-3 scroll-mt-24 md:grid-cols-3">{data.skills.map(group => <article key={group.group} className="skill-card rounded-2xl border border-white/10 bg-black/20 p-5"><h3 className="skill-card-title font-bold text-cyan-300">{group.group}</h3><div className="mt-4 flex flex-wrap gap-2">{group.items.map(item => <span key={item} className="skill-tag rounded-lg border border-white/10 px-2.5 py-1.5 text-xs text-slate-300">{item}</span>)}</div></article>)}</div></div></section>
    <section id="projects" className="scroll-mt-24 py-6"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.25em] text-purple-300">{copy.projects.eyebrow}</p><h2 className="mt-2 text-2xl font-black">{copy.projects.title}</h2></div><span className="inline-flex items-center gap-2 text-xs text-slate-500"><FaceButton label="A" compact /> {copy.projects.enter}</span></div><div className="mt-5 grid gap-4 lg:grid-cols-3">{data.projects.map(project => <article key={project.slug} className="project-card group rounded-2xl border border-white/10 bg-[#071018] p-4 transition hover:-translate-y-1 hover:border-lime-300/40"><div className="flex aspect-video items-center justify-center rounded-xl border border-white/10 bg-gradient-to-br from-slate-900 to-black text-4xl font-black text-lime-300/20">{project.title.split(' ').slice(0,2).map(x=>x[0]).join('')}</div><h3 className="mt-4 font-black">{project.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{project.description}</p><div className="mt-4 flex flex-wrap gap-2">{project.stack.map(tag => <span key={tag} className="project-tag rounded-full bg-lime-300/5 px-2 py-1 text-[10px] text-lime-200">{tag}</span>)}</div><div className="mt-5 flex gap-4"><Link href={`/projects/${project.slug}`} className="inline-flex items-center gap-2 text-xs font-black text-lime-300">{copy.projects.enter} <FaceButton label="A" compact /></Link><a href="#" className="text-xs font-black text-slate-400 hover:text-white">{copy.projects.github}</a></div></article>)}</div></section>
    <section id="experience" className="scroll-mt-24 py-6"><div className="rounded-3xl border border-white/10 bg-[#071018] p-6"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.25em] text-cyan-300">{copy.experience.eyebrow}</p><h2 className="mt-2 text-2xl font-black">{copy.experience.title}</h2></div><span className="text-xs text-slate-500">{copy.experience.description}</span></div><div className="mt-8 space-y-7">{data.experience.map(item => <article key={`${item.company}-${item.period}`} className="relative border-l border-white/10 pl-6"><span className={`absolute -left-[6px] top-1 size-3 rounded-full ${item.current ? 'bg-lime-300' : 'bg-cyan-300'}`}/><div className="flex flex-wrap items-center gap-3"><h3 className="font-black">{item.role}</h3>{item.current && <span className="rounded-full border border-lime-300/30 px-2 py-1 text-[9px] font-black text-lime-300">{copy.experience.current}</span>}</div><p className="mt-1 text-xs text-slate-500">{item.company} · {item.period}</p><ul className="mt-3 space-y-1 text-sm leading-6 text-slate-400">{item.bullets.map(b => <li key={b}>• {b}</li>)}</ul></article>)}</div></div></section>
    <section id="contact" className="scroll-mt-24 py-10"><div className="rounded-3xl border border-purple-400/20 bg-gradient-to-br from-purple-400/5 to-lime-300/5 p-8 text-center"><p className="font-mono text-xs uppercase tracking-[.3em] text-purple-300">{copy.contact.eyebrow}</p><h2 className="mt-3 text-3xl font-black">{copy.contact.title}</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-400">{copy.contact.description}</p><a href="mailto:your@email.com" className="mt-6 inline-flex items-center gap-3 rounded-xl bg-lime-300 px-6 py-3 text-xs font-black text-black">{copy.contact.action}</a></div></section>
    <footer className="border-t border-white/10 py-6 text-center text-xs text-slate-600">{copy.footer}</footer>
  </div></div></main>;
}
